// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sowbcqebuckgctqdrbty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvd2JjcWVidWNrZ2N0cWRyYnR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMjYzMDgsImV4cCI6MjA3MjYwMjMwOH0.AvnFRo2oRDEDPUFrYCP-vZIJ1g0GFjYHsOr-M2Vc_5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});